-- MySQL Script generated by MySQL Workbench
-- Fri Nov 27 01:03:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customers` (
  `idCustomers` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(20) NOT NULL,
  `Surname` VARCHAR(40) NOT NULL,
  `Phone` VARCHAR(15) NOT NULL,
  `Mail` VARCHAR(60) NOT NULL,
  `Pesel` VARCHAR(15) NULL,
  `NIP` VARCHAR(15) NULL,
  `CompanyName` VARCHAR(45) NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Street` VARCHAR(45) NOT NULL,
  `ZipCode` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idCustomers`),
  UNIQUE INDEX `idCustomers_UNIQUE` (`idCustomers` ASC) VISIBLE,
  UNIQUE INDEX `Pesel_UNIQUE` (`Pesel` ASC) VISIBLE,
  UNIQUE INDEX `NIP_UNIQUE` (`NIP` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProjFinance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ProjFinance` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ProjFinance` (
  `idProjFinance` INT NOT NULL AUTO_INCREMENT,
  `Budget` FLOAT NOT NULL,
  `ExpectedProfit` FLOAT NOT NULL,
  `BonusManager` FLOAT NOT NULL,
  `PenaltyPerDay` FLOAT NULL,
  `Costs` FLOAT NOT NULL,
  `AdditionalCosts` FLOAT NOT NULL,
  PRIMARY KEY (`idProjFinance`),
  UNIQUE INDEX `idProjFinance_UNIQUE` (`idProjFinance` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Rules` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Rules` (
  `idRules` INT NOT NULL AUTO_INCREMENT,
  `RuleAccess` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idRules`),
  UNIQUE INDEX `idRules_UNIQUE` (`idRules` ASC) VISIBLE,
  UNIQUE INDEX `RuleAccess_UNIQUE` (`RuleAccess` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Workers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Workers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Workers` (
  `idWorkers` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(25) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Phone` VARCHAR(20) NOT NULL,
  `Mail` VARCHAR(60) NOT NULL,
  `IsActive` TINYINT NOT NULL,
  `Pesel` VARCHAR(15) NOT NULL,
  `Login` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(32) NOT NULL,
  `idRules` INT NULL,
  PRIMARY KEY (`idWorkers`),
  UNIQUE INDEX `idWorkers_UNIQUE` (`idWorkers` ASC) VISIBLE,
  UNIQUE INDEX `Pesel_UNIQUE` (`Pesel` ASC) VISIBLE,
  UNIQUE INDEX `Mail_UNIQUE` (`Mail` ASC) VISIBLE,
  UNIQUE INDEX `Phone_UNIQUE` (`Phone` ASC) VISIBLE,
  INDEX `fk_Workers_Rules_idx` (`idRules` ASC) VISIBLE,
  CONSTRAINT `fk_Workers_Rules`
    FOREIGN KEY (`idRules`)
    REFERENCES `mydb`.`Rules` (`idRules`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Projects` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Projects` (
  `idProjects` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `DateStart` DATE NOT NULL,
  `DateEnd` DATE NOT NULL,
  `State` VARCHAR(45) NULL,
  `Comment` VARCHAR(400) NOT NULL,
  `Area` DOUBLE NOT NULL,
  `idCustomers` INT NULL,
  `idProjFinance` INT NULL,
  `idManager` INT NULL,
  PRIMARY KEY (`idProjects`),
  UNIQUE INDEX `idProjects_UNIQUE` (`idProjects` ASC) VISIBLE,
  INDEX `fk_Projects_Customers_idx` (`idCustomers` ASC) VISIBLE,
  INDEX `fk_Projects_ProjFinance_idx` (`idProjFinance` ASC) VISIBLE,
  INDEX `fk_Projects_Workers_idx` (`idManager` ASC) VISIBLE,
  CONSTRAINT `fk_Projects_Customers`
    FOREIGN KEY (`idCustomers`)
    REFERENCES `mydb`.`Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projects_ProjFinance`
    FOREIGN KEY (`idProjFinance`)
    REFERENCES `mydb`.`ProjFinance` (`idProjFinance`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projects_Workers`
    FOREIGN KEY (`idManager`)
    REFERENCES `mydb`.`Workers` (`idWorkers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DailyRaport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DailyRaport` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DailyRaport` (
  `idDailyRaport` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `idWorkers` INT NULL,
  `idProjects` INT NULL,
  PRIMARY KEY (`idDailyRaport`),
  UNIQUE INDEX `idDailyRaport_UNIQUE` (`idDailyRaport` ASC) VISIBLE,
  INDEX `fk_DailyRaport_Workers_idx` (`idWorkers` ASC) VISIBLE,
  INDEX `fk_DailtRaport_Projects_idx` (`idProjects` ASC) VISIBLE,
  CONSTRAINT `fk_DailyRaport_Workers`
    FOREIGN KEY (`idWorkers`)
    REFERENCES `mydb`.`Workers` (`idWorkers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DailtRaport_Projects`
    FOREIGN KEY (`idProjects`)
    REFERENCES `mydb`.`Projects` (`idProjects`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Contracts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Contracts` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Contracts` (
  `idContracts` INT NOT NULL AUTO_INCREMENT,
  `DateStart` DATE NOT NULL,
  `DateEND` DATE NOT NULL,
  `Position` VARCHAR(45) NOT NULL,
  `RateDay` FLOAT NOT NULL,
  `idWorkers` INT NULL,
  PRIMARY KEY (`idContracts`),
  UNIQUE INDEX `idContracts_UNIQUE` (`idContracts` ASC) VISIBLE,
  INDEX `fk_Contracts_Workers_idx` (`idWorkers` ASC) VISIBLE,
  CONSTRAINT `fk_Contracts_Workers`
    FOREIGN KEY (`idWorkers`)
    REFERENCES `mydb`.`Workers` (`idWorkers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
